name: midfullife
description: "Aplikasi Kesehatan Mental."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dash_chat_2: ^0.0.20
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_gemini: ^0.1.2
  http: ^1.2.0
  lottie: ^3.1.0
  ming_cute_icons: ^0.0.5
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/font/
    - assets/logo/
    - assets/animation/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/login/
    - assets/images/mood/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/font/Urbanist-Light.ttf
          weight: 300
        - asset: assets/font/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/font/Urbanist-Italic.ttf
          style: italic
        - asset: assets/font/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/font/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/font/Urbanist-Bold.ttf
          weight: 800
